services:
  pizzashop:
    container_name: pizzashop
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
        - pizzashop_pg_data:/bitnami/postgresql
volumes:
  pizzashop_pg_data:
